// AUTO-GENERATED by scripts/sync-metrics.sh — do not edit by hand
// Source: content/metrics/latest.json
// Snapshot 2026-08-22: embed pins v0.2.5 / v0.3.6, soak + crash-loop reval.
// Homepage must not headline the 432-cell mean vs PostgreSQL (25×).

export const PUBLIC_METRICS = {
  collected_at: "20260822T120000Z",
  git_commit: "bd52a3c",
  benchmarks_status: "fresh",
  tests_total: 5597,
  tests_by_package: {
    "f4kvs-core": 1227,
    "f4kvs-network": 109,
    "f4kvs-server": 329,
    "f4kvs-client": 368,
    "f4kvs-clustering": 630,
    "f4kvs-ql": 1627,
    "f4kvs-e2e": 9,
    "f4kvs-autoconfig": 20,
    "f4kvs-observability": 87,
    "f4kvs-ttl": 65,
    "f4kvs-storage-memory": 3,
  },
  coverage_lines_percent: 67.57,
  postgres_speedup_min: 3.7,
  postgres_speedup_max: 4.5,
  postgres_speedup_avg: 4.1,
  scylla_speedup_min: 2.0,
  scylla_speedup_max: 3.8,
  scylla_speedup_avg: 2.63,
  latency_p50_min: 0.04,
  latency_p50_max: 0.09,
  latency_p99_min: 0.17,
  latency_p99_max: 0.46,
  methodology:
    "YCSB A/B/D, 10K records, 512B values, 4 workers, 30s per workload, partitioned storage (server path)",
  ql_tests: 1627,
  clustering_tests: 630,
  ops_proof: {
    docker_staging_smoke: {
      passed: true,
      date: "2026-07-11",
      tests_passed: 2,
      artifact: "staging-results/docker-staging-20260711T094639Z.txt",
    },
    docker_staging_join_leave: {
      passed: true,
      date: "2026-07-05",
      tests_passed: 3,
      artifact: "staging-results/docker-staging-20260705T211248Z.txt",
    },
    soak_pilot: {
      passed: true,
      date: "2026-08-17",
      tier: "pilot",
      duration_secs: 300,
      health_failures: 0,
      anchors_verified: true,
      artifact: "staging-results/soak-20260817T194744Z/",
    },
    soak_full: {
      passed: true,
      date: "2026-07-11",
      tier: "full",
      ops_per_workload: 50000,
      health_failures: 0,
      anchors_verified: true,
      artifact: "staging-results/soak-20260711T125039Z/",
    },
    soak_sustained: {
      passed: true,
      date: "2026-08-18",
      tier: "sustained",
      duration_hours: 2,
      cache_ops: 1661444,
      cache_ops_per_s: 462,
      anchors_verified: true,
      health_failures: 0,
      artifact: "staging-results/soak-20260818T023658Z/",
    },
    crash_loop: {
      passed: true,
      date: "2026-08-17",
      rounds: 50,
      ops_per_round: 1000,
      loss: 0,
      artifact: "staging-results/soak-20260817T200639Z/",
    },
    ql_gate_smoke: {
      passed: true,
      date: "2026-07-05",
      tests_passed: 71,
      artifact: "staging-results/ql-gate-smoke-20260705T205815Z.txt",
    },
    cluster_scenarios: {
      passed: true,
      date: "2026-07-19",
      tests_passed: 9,
      tests_total: 9,
      artifact: "tools/test-scenarios/run-scenarios.sh",
    },
    cluster_hostile_memory: {
      passed: true,
      date: "2026-07-20",
      tests_passed: 4,
      tests_total: 4,
      artifact: "tools/test-scenarios/run-hostile.sh",
    },
    cluster_hostile_persistent: {
      passed: true,
      date: "2026-07-20",
      tests_passed: 5,
      tests_total: 5,
      artifact: "tools/test-scenarios/run-hostile-persistent.sh",
    },
    alpha_embed_go: {
      passed: true,
      date: "2026-07-23",
      scope:
        "f4kvs-ffi v0.2.5 + f4kvs-lsm v0.3.6 for memoirs/RAG preprod; cluster remains lab",
      artifact: "PROD_CHECKLIST.md",
    },
  },
  releases: {
    f4kvs_lsm: "v0.3.6",
    f4kvs_ffi: "v0.2.5",
    f4kvs_v2: "v0.2.0",
    f4kvs_v2_head: "bd52a3c",
    notes: "embed train for memoirs/RAG; cluster remains lab",
  },
  de_bench: {
    flow_id: "rag_chunk_ingest_v1",
    run_id: "native-fair-20260724",
    tier: "meso",
    schema: "bench-schema-v1",
    scale: { chunks: 100000, chunk_bytes: 4096, memoirs: 50, random_gets: 5000 },
    integrity_ok: true,
    row_count: 100050,
    results: {
      f4kvs: {
        bulk_ingest_ops_per_s: 61000,
        prefix_scan_ms: 2,
        random_get_ops_per_s: 36000,
      },
    },
    notes:
      "Public summary: native engine one-shot bulk + integrity. Not a RocksDB pitch.",
  },
  server_perf: {
    date: "2026-08-18",
    git: "f52790c",
    ops: 20000,
    put_ops_per_s: 9070,
    get_ops_per_s: 29412,
    mixed_ops_per_s: 37594,
    errors: 0,
    artifact: "benchmark_results/perf-history.jsonl",
  },
  matrix_h2h: {
    collected_at: "20260803T075201Z",
    git_commit: "3158587",
    mode: "modes_long_h2h_432",
    vs_postgresql: { speedup_median: 9.49, speedup_min: 0.8, speedup_max: 143.82, n: 144 },
    vs_scylladb: { speedup_median: 1.85, speedup_min: 0.11, speedup_max: 2.9, n: 142 },
    methodology:
      "432-cell multi-system matrix; 60s measurement. Headline the median — some QL cells lose.",
  },
} as const;

export function metricsCollectedLabel(): string {
  const d = PUBLIC_METRICS.collected_at;
  if (d.length >= 8) return d.slice(0, 4) + "-" + d.slice(4, 6) + "-" + d.slice(6, 8);
  return d;
}

export function postgresSpeedupRange(): string {
  const m = PUBLIC_METRICS;
  if (m.postgres_speedup_min === m.postgres_speedup_max)
    return `${m.postgres_speedup_avg}x`;
  return `${m.postgres_speedup_min}–${m.postgres_speedup_max}x`;
}

export function benchmarksFresh(): boolean {
  return PUBLIC_METRICS.benchmarks_status === "fresh";
}

export function opsProofComplete(): boolean {
  const o = PUBLIC_METRICS.ops_proof;
  if (!o) return false;
  return Boolean(
    o.docker_staging_smoke?.passed &&
      o.docker_staging_join_leave?.passed &&
      o.soak_pilot?.passed &&
      o.ql_gate_smoke?.passed
  );
}

export function deBenchReady(): boolean {
  const d = PUBLIC_METRICS.de_bench;
  return Boolean(d && d.integrity_ok && d.tier);
}

export function alphaEmbedGo(): boolean {
  return Boolean(PUBLIC_METRICS.ops_proof?.alpha_embed_go?.passed);
}

export function crashLoopReady(): boolean {
  const c = PUBLIC_METRICS.ops_proof?.crash_loop;
  return Boolean(c && c.passed && c.loss === 0);
}

export function soakSustainedReady(): boolean {
  return Boolean(PUBLIC_METRICS.ops_proof?.soak_sustained?.passed);
}

export function embedPinsLabel(): string {
  const r = PUBLIC_METRICS.releases;
  if (!r) return "FFI + LSM";
  return `${r.f4kvs_ffi} + ${r.f4kvs_lsm}`;
}
