// AUTO-GENERATED by scripts/sync-metrics.sh — do not edit by hand
// Source: content/metrics/latest.json

export const PUBLIC_METRICS = {"collected_at":"20260709T215748Z","git_commit":"a7a8f90","benchmarks_status":"fresh","tests_total":4474,"tests_by_package":{"f4kvs-core":1227,"f4kvs-network":109,"f4kvs-server":329,"f4kvs-client":368,"f4kvs-clustering":630,"f4kvs-ql":1627,"f4kvs-e2e":9,"f4kvs-autoconfig":20,"f4kvs-observability":87,"f4kvs-ttl":65,"f4kvs-storage-memory":3},"coverage_lines_percent":67.56296330401952,"postgres_speedup_min":3.6,"postgres_speedup_max":4.8,"postgres_speedup_avg":4.23,"scylla_speedup_min":2.0,"scylla_speedup_max":3.8,"scylla_speedup_avg":2.63,"latency_p50_min":0.04,"latency_p50_max":0.09,"latency_p99_min":0.17,"latency_p99_max":0.46,"methodology":"YCSB A/B/D, 10K records, 512B values, 4 workers, 30s per workload, partitioned storage","ql_tests":1627,"clustering_tests":630,"ops_proof":{"docker_staging_smoke":{"passed":true,"date":"2026-07-05","tests_passed":2,"artifact":"staging-results/docker-staging-20260705T210307Z.txt"},"docker_staging_join_leave":{"passed":true,"date":"2026-07-05","tests_passed":3,"artifact":"staging-results/docker-staging-20260705T211248Z.txt"},"soak_pilot":{"passed":true,"date":"2026-07-05","tier":"pilot","duration_secs":300,"health_failures":0,"anchors_verified":true,"artifact":"staging-results/soak-20260705T212216Z/"},"ql_gate_smoke":{"passed":true,"date":"2026-07-05","tests_passed":71,"artifact":"staging-results/ql-gate-smoke-20260705T205815Z.txt"}}} as const;

export function metricsCollectedLabel(): string {
  const d = PUBLIC_METRICS.collected_at;
  if (d.length >= 8) return d.slice(0, 4) + "-" + d.slice(4, 6) + "-" + d.slice(6, 8);
  return d;
}

export function postgresSpeedupRange(): string {
  const m = PUBLIC_METRICS;
  if (m.postgres_speedup_min === m.postgres_speedup_max)
    return `${m.postgres_speedup_avg}x`;
  return `${m.postgres_speedup_min}–${m.postgres_speedup_max}x`;
}

export function benchmarksFresh(): boolean {
  return PUBLIC_METRICS.benchmarks_status === "fresh";
}

export function opsProofComplete(): boolean {
  const o = PUBLIC_METRICS.ops_proof;
  if (!o) return false;
  return Boolean(
    o.docker_staging_smoke?.passed &&
    o.docker_staging_join_leave?.passed &&
    o.soak_pilot?.passed &&
    o.ql_gate_smoke?.passed
  );
}
