#!/usr/bin/env bash
# Sync f4kvs-v2 metrics JSON into the Astro site config.
#
# Usage:
#   ./scripts/sync-metrics.sh [path/to/pugdb-metrics-latest.json]
#
# Default source: first existing path among:
#   ~/work/dev/rust/f4kvs-v2/metrics/pugdb-metrics-latest.json
#   ~/dev/rust/f4kvs-v2/metrics/pugdb-metrics-latest.json

set -euo pipefail

SITE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEFAULT_SRC=""
for candidate in \
  "$HOME/work/dev/rust/f4kvs-v2/metrics/pugdb-metrics-latest.json" \
  "$HOME/dev/rust/f4kvs-v2/metrics/pugdb-metrics-latest.json"; do
  if [[ -f "$candidate" ]]; then
    DEFAULT_SRC="$candidate"
    break
  fi
done

SRC="${1:-$DEFAULT_SRC}"
DEST_JSON="$SITE_ROOT/content/metrics/latest.json"
DEST_TS="$SITE_ROOT/src/config/metrics.ts"

if [[ -z "$SRC" || ! -f "$SRC" ]]; then
  echo "Metrics file not found." >&2
  echo "Run: f4kvs-v2/scripts/metrics/collect-pugdb-metrics.sh" >&2
  exit 1
fi

mkdir -p "$(dirname "$DEST_JSON")"
cp "$SRC" "$DEST_JSON"

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi

# Normalize fields the site expects (derived + raw).
jq '
  .site = {
    tests_total: .quality.tests_total,
    tests_by_package: .quality.tests_by_package,
    coverage: .quality.coverage,
    benchmarks: .benchmarks,
    benchmarks_status: .benchmarks_status,
    collected_at: .collected_at,
    git_commit: .git.commit,
    ops_proof: (.operations.ops_proof // null)
  }
' "$DEST_JSON" > "${DEST_JSON}.tmp" && mv "${DEST_JSON}.tmp" "$DEST_JSON"

# Generate TypeScript module for Astro imports.
jq -r '
  def bench_pg:
    if .benchmarks.vs_postgresql then
      .benchmarks.vs_postgresql
    else
      {speedup_min: 4.3, speedup_max: 7.9, speedup_avg: 5.8}
    end;
  def bench_scylla:
    if .benchmarks.vs_scylladb then
      .benchmarks.vs_scylladb
    else
      {speedup_min: 2.3, speedup_max: 4.4, speedup_avg: 3.5}
    end;
  def lat:
    if .benchmarks.latency_ms then .benchmarks.latency_ms
    else {p50_min: 0.029, p50_max: 0.072, p99_min: 0.076, p99_max: 0.272}
    end;
  def ops:
    if .operations.ops_proof then .operations.ops_proof else null end;
  {
    collected_at: .collected_at,
    git_commit: .git.commit,
    benchmarks_status: .benchmarks_status,
    tests_total: .quality.tests_total,
    tests_by_package: .quality.tests_by_package,
    coverage_lines_percent: (.quality.coverage.lines_percent // null),
    postgres_speedup_min: (bench_pg | .speedup_min),
    postgres_speedup_max: (bench_pg | .speedup_max),
    postgres_speedup_avg: (bench_pg | .speedup_avg),
    scylla_speedup_min: (bench_scylla | .speedup_min),
    scylla_speedup_max: (bench_scylla | .speedup_max),
    scylla_speedup_avg: (bench_scylla | .speedup_avg),
    latency_p50_min: (lat | .p50_min),
    latency_p50_max: (lat | .p50_max),
    latency_p99_min: (lat | .p99_min),
    latency_p99_max: (lat | .p99_max),
    methodology: (.benchmarks.methodology // "YCSB workloads; see metrics campaign doc"),
    ql_tests: (.quality.tests_by_package["f4kvs-ql"] // 0),
    clustering_tests: (.quality.tests_by_package["f4kvs-clustering"] // 0),
    ops_proof: ops,
    releases: (.releases // null),
    de_bench: (.de_bench // null),
    server_perf: (.server_perf // null),
    matrix_h2h: (if .matrix_h2h then {
      collected_at: .matrix_h2h.collected_at,
      git_commit: .matrix_h2h.git_commit,
      mode: .matrix_h2h.mode,
      vs_postgresql: {
        speedup_median: .matrix_h2h.vs_postgresql.speedup_median,
        speedup_min: .matrix_h2h.vs_postgresql.speedup_min,
        speedup_max: .matrix_h2h.vs_postgresql.speedup_max,
        n: (.matrix_h2h.vs_postgresql.workloads_measured // .matrix_h2h.vs_postgresql.n)
      },
      vs_scylladb: {
        speedup_median: .matrix_h2h.vs_scylladb.speedup_median,
        speedup_min: .matrix_h2h.vs_scylladb.speedup_min,
        speedup_max: .matrix_h2h.vs_scylladb.speedup_max,
        n: (.matrix_h2h.vs_scylladb.workloads_measured // .matrix_h2h.vs_scylladb.n)
      },
      methodology: .matrix_h2h.methodology
    } else null end)
  }
' "$DEST_JSON" | jq -r '
  "// AUTO-GENERATED by scripts/sync-metrics.sh — do not edit by hand",
  "// Source: content/metrics/latest.json",
  "",
  "export const PUBLIC_METRICS = " + (. | tojson) + " as const;",
  "",
  "export function metricsCollectedLabel(): string {",
  "  const d = PUBLIC_METRICS.collected_at;",
  "  if (d.length >= 8) return d.slice(0, 4) + \"-\" + d.slice(4, 6) + \"-\" + d.slice(6, 8);",
  "  return d;",
  "}",
  "",
  "export function postgresSpeedupRange(): string {",
  "  const m = PUBLIC_METRICS;",
  "  if (m.postgres_speedup_min === m.postgres_speedup_max)",
  "    return `${m.postgres_speedup_avg}x`;",
  "  return `${m.postgres_speedup_min}–${m.postgres_speedup_max}x`;",
  "}",
  "",
  "export function benchmarksFresh(): boolean {",
  "  return PUBLIC_METRICS.benchmarks_status === \"fresh\";",
  "}",
  "",
  "export function opsProofComplete(): boolean {",
  "  const o = PUBLIC_METRICS.ops_proof;",
  "  if (!o) return false;",
  "  return Boolean(",
  "    o.docker_staging_smoke?.passed &&",
  "    o.docker_staging_join_leave?.passed &&",
  "    o.soak_pilot?.passed &&",
  "    o.ql_gate_smoke?.passed",
  "  );",
  "}",
  "",
  "export function deBenchReady(): boolean {",
  "  const d = PUBLIC_METRICS.de_bench;",
  "  return Boolean(d && d.integrity_ok && d.tier);",
  "}",
  "",
  "export function alphaEmbedGo(): boolean {",
  "  return Boolean(PUBLIC_METRICS.ops_proof?.alpha_embed_go?.passed);",
  "}",
  "",
  "export function crashLoopReady(): boolean {",
  "  const c = PUBLIC_METRICS.ops_proof?.crash_loop;",
  "  return Boolean(c && c.passed && c.loss === 0);",
  "}",
  "",
  "export function soakSustainedReady(): boolean {",
  "  return Boolean(PUBLIC_METRICS.ops_proof?.soak_sustained?.passed);",
  "}",
  "",
  "export function embedPinsLabel(): string {",
  "  const r = PUBLIC_METRICS.releases;",
  "  if (!r) return \"FFI + LSM\";",
  "  return `${r.f4kvs_ffi} + ${r.f4kvs_lsm}`;",
  "}"
' > "$DEST_TS"

echo "Synced from $SRC:"
echo "  $DEST_JSON"
echo "  $DEST_TS"